- name: crée le répertoire Temp
  ansible.windows.win.file:
    path: C:\Temp
    state: directory

- name: Copier le script PowerShell Zabbix sur la machine
  template:
    src: script_deploiement_agent.ps1
    dest: C:\Temp\script_deploiement_agent.ps1

- name: Exécuter le script PowerShell
  win_shell: |
    powershell.exe -ExecutionPolicy Bypass -File C:\Temp\script_deploiement_agent.ps1
